// Blog post data with rich content support
// Each content item can be a paragraph, heading, list, code block, or callout

export interface ContentBlock {
  type: 'paragraph' | 'heading' | 'subheading' | 'list' | 'code' | 'callout' | 'quote' | 'image';
  content?: string;
  items?: string[];
  language?: string;
  variant?: 'info' | 'warning' | 'tip' | 'stat';
  alt?: string;
  src?: string;
}

export interface BlogPost {
  id: string;
  title: string;
  excerpt: string;
  metaDescription: string;
  image: string;
  category: string;
  date: string;
  readTime: string;
  author: string;
  authorRole?: string;
  tags: string[];
  content: ContentBlock[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "claude-code-complete-guide",
    title: "Claude Code: The Complete Guide to AI-Powered Development in 2026",
    excerpt: "Master Claude Code, the AI coding assistant that's transforming how developers build software. From setup to advanced workflows, learn everything you need to 10x your productivity.",
    metaDescription: "Complete guide to Claude Code - the AI coding assistant with 80.9% SWE-bench accuracy. Learn setup, CLAUDE.md configuration, MCP integrations, hooks, and productivity tips.",
    image: "/blog/claude-code-guide.jpg",
    category: "AI & Engineering",
    date: "March 13, 2026",
    readTime: "15 min read",
    author: "M.D.N Tech Team",
    authorRole: "AI Development Experts",
    tags: ["Claude Code", "AI Development", "Productivity", "Developer Tools", "Agentic AI"],
    content: [
      {
        type: "paragraph",
        content: "The software development landscape has fundamentally shifted. In just eight months, Claude Code went from launch to becoming the most-loved AI coding tool among developers. With an 80.9% accuracy on SWE-bench Verified — the current industry record — it's not just another autocomplete tool. It's a paradigm shift in how we build software."
      },
      {
        type: "callout",
        variant: "stat",
        content: "4% of all public commits on GitHub are now generated by Claude Code, with projections reaching 20%+ by year-end 2026."
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, we've integrated Claude Code into every project we deliver. This guide shares everything we've learned — from basic setup to advanced workflows that have helped us ship production-ready systems in weeks instead of months."
      },
      {
        type: "heading",
        content: "What is Claude Code?"
      },
      {
        type: "paragraph",
        content: "Claude Code is Anthropic's AI-powered coding assistant that understands your entire codebase. Unlike traditional code completion tools, it operates with deep contextual awareness — analyzing full repositories rather than just immediate context. This makes it exceptional for complex refactoring, architectural decisions, and multi-file changes."
      },
      {
        type: "paragraph",
        content: "It runs as a CLI in your terminal, integrates with VS Code and Cursor, and can even run in your browser. The key difference from competitors? Claude Code doesn't just suggest code — it reasons about your architecture, explains trade-offs, and acts as a collaborative engineering partner."
      },
      {
        type: "callout",
        variant: "info",
        content: "Claude Code's VS Code extension went from 17.7 million daily installs to 29 million since January 2026 — and continues rising exponentially."
      },
      {
        type: "heading",
        content: "The Numbers: Why Developers Are Switching"
      },
      {
        type: "paragraph",
        content: "The productivity gains aren't hype. Academic research and enterprise case studies consistently show 26-55% productivity improvements, with experienced developers seeing the largest gains. But some results are even more dramatic:"
      },
      {
        type: "list",
        items: [
          "Average task completion: 3.1 hours → 15 minutes (92% reduction)",
          "One developer delivered a '4 people × 6 months' project in 2 months alone — a 12x multiplier",
          "Engineers report 164% increase in story completion rates",
          "Pull request merge rates nearly doubled in some teams",
          "A Google principal engineer reported Claude reproduced a year of architectural work in one hour"
        ]
      },
      {
        type: "paragraph",
        content: "When developers were asked which tool they rely on for complex tasks (multi-file refactoring, architecture design, debugging), Claude was the top choice at 44%, followed by GitHub Copilot (28%) and ChatGPT (19%)."
      },
      {
        type: "heading",
        content: "Getting Started: Essential Setup"
      },
      {
        type: "subheading",
        content: "Installation"
      },
      {
        type: "paragraph",
        content: "Claude Code runs in your terminal and integrates with your existing workflow. Install it via npm, Homebrew, or the VS Code extension marketplace. For the best experience, we recommend the terminal CLI combined with VS Code integration."
      },
      {
        type: "paragraph",
        content: "Installation is straightforward: use npm to install globally, or Homebrew on macOS. Once installed, verify with the version command. The VS Code extension is available in the marketplace — search for 'Claude Code' and install with one click."
      },
      {
        type: "subheading",
        content: "The CLAUDE.md File: Your Project's AI Memory"
      },
      {
        type: "paragraph",
        content: "CLAUDE.md is the secret weapon most developers underutilize. It's a markdown file at your project root that Claude reads at the start of every session. Think of it as persistent context — your coding standards, architecture decisions, preferred libraries, and workflows."
      },
      {
        type: "paragraph",
        content: "A well-structured CLAUDE.md includes several key sections: Project Overview (what the project does), Tech Stack (framework, database, styling, state management), Code Style (naming conventions, module patterns), Commands (dev, test, lint, build), and Architecture Rules (where files should live, patterns to follow). The more specific you are, the better Claude understands your codebase."
      },
      {
        type: "callout",
        variant: "tip",
        content: "Run /init to generate a starter CLAUDE.md based on your current project structure. Claude examines your codebase — package files, configs, code patterns — and creates a tailored starting point."
      },
      {
        type: "paragraph",
        content: "Best practices for CLAUDE.md:"
      },
      {
        type: "list",
        items: [
          "Keep it under 200 lines — concise and actionable",
          "Use progressive disclosure — tell Claude how to find info, not everything at once",
          "Include actual commands you use, not generic ones",
          "Document architecture decisions that aren't obvious from code",
          "Commit to version control so the whole team benefits"
        ]
      },
      {
        type: "heading",
        content: "MCP: Connecting Claude to Your Tools"
      },
      {
        type: "paragraph",
        content: "The Model Context Protocol (MCP) is what transforms Claude Code from a coding assistant into an integrated development platform. MCP is an open standard — think of it as 'USB-C for AI' — that lets Claude connect to external tools, databases, and APIs."
      },
      {
        type: "paragraph",
        content: "With MCP, Claude Code can:"
      },
      {
        type: "list",
        items: [
          "Read design documents from Google Drive",
          "Update tickets in Jira or Linear",
          "Pull context from Slack conversations",
          "Query your databases directly",
          "Interact with your CI/CD pipeline",
          "Use custom internal tooling"
        ]
      },
      {
        type: "paragraph",
        content: "Early adopters like Block and Apollo have integrated MCP into their systems. Development platforms including Zed, Replit, Codeium, and Sourcegraph are building native MCP support."
      },
      {
        type: "callout",
        variant: "warning",
        content: "Security note: Only use MCP servers you trust. Be especially careful with servers that fetch untrusted content, as they can expose you to prompt injection risks."
      },
      {
        type: "heading",
        content: "Hooks: Guaranteed Automation"
      },
      {
        type: "paragraph",
        content: "Hooks are shell commands that run automatically at specific points during your Claude Code session. The critical difference from prompt-based instructions? Hooks are guaranteed to execute."
      },
      {
        type: "quote",
        content: "If you tell Claude in your CLAUDE.md not to modify .env files, it will probably listen. If you set up a PreToolUse hook that blocks writes to .env files, it will always block them. For production codebases or regulated environments, that distinction between 'probably' and 'always' is everything."
      },
      {
        type: "paragraph",
        content: "Common hook use cases:"
      },
      {
        type: "list",
        items: [
          "Auto-format code after every file edit",
          "Run linting before commits",
          "Execute tests automatically after changes",
          "Block dangerous database operations without confirmation",
          "Send Slack notifications on task completion",
          "Create automatic backups before major changes"
        ]
      },
      {
        type: "paragraph",
        content: "Setting up hooks is done through your settings file. For example, a PostToolUse hook with a 'Write' matcher can automatically run Prettier on any file Claude edits. The hook triggers after the file is written, formats it, and saves — all without manual intervention."
      },
      {
        type: "paragraph",
        content: "Claude Code supports 15 different hook events and three handler types (command, HTTP, and prompt). The prompt hook type is unique — it lets you delegate hook decisions to an LLM without writing custom code."
      },
      {
        type: "heading",
        content: "Latest Features (March 2026)"
      },
      {
        type: "paragraph",
        content: "Claude Code is evolving rapidly. Here are the newest capabilities:"
      },
      {
        type: "subheading",
        content: "Agent Teams (Research Preview)"
      },
      {
        type: "paragraph",
        content: "Multi-agent collaboration where teams of AI agents work together on complex tasks. Enable with CLAUDE_CODE_EXPERIMENTAL_AGENT_TEAMS=1. This is token-intensive but powerful for large-scale refactoring or feature development."
      },
      {
        type: "subheading",
        content: "Automatic Memory"
      },
      {
        type: "paragraph",
        content: "Claude now automatically records and recalls relevant context as it works. No more re-explaining your project every session."
      },
      {
        type: "subheading",
        content: "/loop Command"
      },
      {
        type: "paragraph",
        content: "Run prompts on a recurring interval. Perfect for monitoring deploys, watching build status, or scheduled maintenance tasks:"
      },
      {
        type: "paragraph",
        content: "Simply type '/loop' followed by an interval and your instruction. For example, '/loop 5m check the deploy status' monitors deployments every 5 minutes, while '/loop 1h run the test suite and report failures' provides hourly test reports. Claude continues the loop until you stop it or close the session."
      },
      {
        type: "subheading",
        content: "Claude in Chrome (Beta)"
      },
      {
        type: "paragraph",
        content: "Control your browser directly from Claude Code. Useful for testing, scraping documentation, or automating web-based workflows."
      },
      {
        type: "subheading",
        content: "Opus 4.6 with Effort Levels"
      },
      {
        type: "paragraph",
        content: "The latest Opus 4.6 model defaults to medium effort for Max subscribers. Effort levels are now simplified to low/medium/high with visual indicators (○ ◐ ●). Use /effort auto to reset to default behavior."
      },
      {
        type: "heading",
        content: "Claude Code vs. The Competition"
      },
      {
        type: "paragraph",
        content: "The AI coding landscape in 2026 has three major players. Here's how they compare:"
      },
      {
        type: "subheading",
        content: "GitHub Copilot"
      },
      {
        type: "paragraph",
        content: "Best for: Inline autocompletion, familiar patterns, boilerplate code. Copilot excels when you're writing code you've written before — CRUD operations, API endpoints, form validation. The suggestions appear before you finish thinking. At $10/month, it's the most affordable option for casual use."
      },
      {
        type: "subheading",
        content: "Cursor"
      },
      {
        type: "paragraph",
        content: "Best for: Multi-file context, project-aware suggestions, power users. Cursor understands your entire codebase and suggests changes across multiple files while maintaining consistency. It's the favorite for complex refactors and new feature development. The multi-file context isn't just nice-to-have — it's a fundamentally different way of working with AI."
      },
      {
        type: "subheading",
        content: "Claude Code"
      },
      {
        type: "paragraph",
        content: "Best for: Complex reasoning, architecture decisions, learning, debugging. Claude stands out for dialogue-based problem solving. It doesn't just suggest code — it explains the reasoning behind solutions, helping you understand trade-offs. This educational aspect is a game-changer for tackling complex issues."
      },
      {
        type: "callout",
        variant: "tip",
        content: "The winning combination for serious developers: Cursor Pro ($20) + Claude Pro ($20) = $40/month total. That's the cost of 30 minutes of freelance development time."
      },
      {
        type: "heading",
        content: "Real-World Workflow: How We Use Claude Code"
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, Claude Code is integrated into every phase of development:"
      },
      {
        type: "list",
        items: [
          "Discovery: We use Claude to analyze existing codebases, understand architecture decisions, and identify technical debt",
          "Architecture: Claude helps design system architecture, suggesting patterns based on our specific requirements and constraints",
          "Implementation: Multi-file features, complex refactoring, and boilerplate generation happen 5-10x faster",
          "Testing: Claude writes comprehensive test suites, identifies edge cases we'd miss, and fixes failing tests",
          "Code Review: Before human review, Claude analyzes PRs for bugs, security issues, and style inconsistencies",
          "Documentation: API docs, README files, and inline comments are generated and kept in sync automatically"
        ]
      },
      {
        type: "paragraph",
        content: "The result? We deliver production-ready systems in weeks, not months. Single engineers own entire features end-to-end. And the code quality is higher because we spend less time on boilerplate and more time on architecture."
      },
      {
        type: "heading",
        content: "The Future: What's Coming"
      },
      {
        type: "paragraph",
        content: "Claude Code is changing how developers think about their role. As one Stripe engineer noted: 'It's evolving the mentality from just writing code to becoming like an architect, almost like a product manager.'"
      },
      {
        type: "paragraph",
        content: "We're seeing early signs of what's next:"
      },
      {
        type: "list",
        items: [
          "Agent teams that can tackle entire features autonomously",
          "Deeper IDE integration with real-time collaboration",
          "Project-level understanding that persists across sessions",
          "Integration with design tools for end-to-end product development",
          "Voice-driven development workflows"
        ]
      },
      {
        type: "paragraph",
        content: "Recruitment studies show developers increasingly don't want to work without AI assistance. The tools are no longer optional — they're becoming as essential as the IDE itself."
      },
      {
        type: "heading",
        content: "Getting Started Today"
      },
      {
        type: "paragraph",
        content: "Ready to transform your development workflow? Here's the quickest path:"
      },
      {
        type: "list",
        items: [
          "Install Claude Code CLI and VS Code extension",
          "Run /init in your project to generate a CLAUDE.md",
          "Customize CLAUDE.md with your specific patterns and commands",
          "Start with simple tasks — file edits, test generation, documentation",
          "Gradually expand to complex refactoring and architecture work",
          "Set up hooks for automation as your workflow matures"
        ]
      },
      {
        type: "callout",
        variant: "info",
        content: "Claude Code is available on the Pro plan ($20/month) with Sonnet 4.5, or Max plan ($100-200/month) for Opus 4.6. The free tier works for occasional use and learning."
      },
      {
        type: "heading",
        content: "Conclusion"
      },
      {
        type: "paragraph",
        content: "Claude Code isn't just another developer tool — it's a fundamental shift in how software gets built. The developers who master these workflows now will have a significant advantage as AI-native development becomes the standard."
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, we've seen firsthand how Claude Code accelerates delivery without sacrificing quality. Whether you're a solo developer or leading a team, the productivity gains are real and substantial."
      },
      {
        type: "paragraph",
        content: "The question isn't whether to adopt AI coding tools — it's how quickly you can integrate them into your workflow. Start today, and you'll wonder how you ever coded without them."
      }
    ]
  },
  {
    id: "agentic-ai-systems-guide",
    title: "Agentic AI Systems: How Autonomous Agents Are Transforming Enterprise Software",
    excerpt: "From single-task assistants to multi-agent swarms — explore the architecture, protocols, and real-world adoption of agentic AI systems reshaping how businesses operate.",
    metaDescription: "Complete guide to agentic AI systems in 2026. Learn about multi-agent architectures, MCP and A2A protocols, enterprise adoption rates, and how autonomous AI agents are transforming industries.",
    image: "/blog/agentic-ai-systems.jpg",
    category: "AI & Engineering",
    date: "March 10, 2026",
    readTime: "16 min read",
    author: "M.D.N Tech Team",
    authorRole: "AI Development Experts",
    tags: ["Agentic AI", "AI Agents", "Multi-Agent Systems", "MCP", "Enterprise AI", "Autonomous Systems"],
    content: [
      {
        type: "paragraph",
        content: "We've crossed a threshold. AI systems are no longer just tools that respond to prompts — they're autonomous agents that plan, execute, and adapt. In 2026, agentic AI has moved from research curiosity to enterprise infrastructure, with over 52% of organizations already deploying AI agents in production workflows."
      },
      {
        type: "callout",
        variant: "stat",
        content: "The agentic AI market reached $6.96 billion in 2025 and is projected to hit $57.42 billion by 2031 — a compound annual growth rate of 42%."
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, we've been building agentic systems for clients across industries — from autonomous customer support agents to multi-agent development workflows. This guide shares what we've learned about architecting, deploying, and scaling AI agents in production environments."
      },
      {
        type: "heading",
        content: "What Makes an AI System 'Agentic'?"
      },
      {
        type: "paragraph",
        content: "The distinction between a chatbot and an agent isn't just semantic — it's architectural. Traditional AI assistants respond to individual queries in isolation. Agentic systems operate autonomously toward goals, using tools, making decisions, and adapting based on outcomes."
      },
      {
        type: "paragraph",
        content: "An agentic system has four defining characteristics:"
      },
      {
        type: "list",
        items: [
          "Autonomy: Operates independently without step-by-step human guidance",
          "Tool Use: Interacts with external systems — APIs, databases, browsers, file systems",
          "Planning: Decomposes complex goals into executable sub-tasks",
          "Feedback Loops: Observes results and adjusts approach dynamically"
        ]
      },
      {
        type: "paragraph",
        content: "The shift from AI assistants to AI agents mirrors the evolution from calculators to computers. A calculator responds to inputs; a computer runs programs. Agents don't just answer questions — they accomplish objectives."
      },
      {
        type: "heading",
        content: "Enterprise Adoption: The Numbers"
      },
      {
        type: "paragraph",
        content: "The adoption curve for agentic AI has been remarkably steep. What started as experimental deployments in 2024 has become mainstream enterprise infrastructure."
      },
      {
        type: "list",
        items: [
          "52% of enterprises have deployed AI agents in production environments",
          "85% have integrated agents into existing business processes",
          "79% of organizations have adopted agentic AI to some degree",
          "40% of applications will embed AI agents by 2027 (Gartner projection)",
          "90% of customer interactions will involve AI agents by 2030"
        ]
      },
      {
        type: "callout",
        variant: "warning",
        content: "Reality check: Despite high adoption rates, 90% of legacy AI agents fail to meet production standards. Success requires purpose-built architecture, not retrofitted chatbots."
      },
      {
        type: "paragraph",
        content: "The gap between deployment and success explains why agentic AI expertise has become one of the most valuable engineering skills. Teams that understand agent architecture, failure modes, and production patterns are delivering outcomes that were impossible two years ago."
      },
      {
        type: "heading",
        content: "Multi-Agent Architectures: Design Patterns"
      },
      {
        type: "paragraph",
        content: "Single agents hit limits quickly. Complex tasks require coordination between specialized agents — each with distinct capabilities, tools, and responsibilities. Google's research identified eight fundamental patterns for multi-agent systems:"
      },
      {
        type: "subheading",
        content: "1. Sequential Pipeline"
      },
      {
        type: "paragraph",
        content: "Agents execute in order, each passing output to the next. Simple to implement, easy to debug. Best for linear workflows like document processing: extraction → validation → summarization → storage."
      },
      {
        type: "subheading",
        content: "2. Parallel Fan-Out"
      },
      {
        type: "paragraph",
        content: "Multiple agents work simultaneously on independent subtasks. Results are aggregated by a coordinator. Ideal for research tasks, competitive analysis, or any work that can be partitioned."
      },
      {
        type: "subheading",
        content: "3. Hierarchical Delegation"
      },
      {
        type: "paragraph",
        content: "A manager agent delegates to specialist sub-agents, reviews their work, and synthesizes results. Mirrors organizational structure. Effective for complex projects requiring diverse expertise."
      },
      {
        type: "subheading",
        content: "4. Debate and Consensus"
      },
      {
        type: "paragraph",
        content: "Multiple agents propose solutions, critique each other's approaches, and converge on consensus. Reduces individual agent errors through adversarial review. Powerful for high-stakes decisions."
      },
      {
        type: "subheading",
        content: "5. Blackboard Architecture"
      },
      {
        type: "paragraph",
        content: "Agents share a common workspace (blackboard) where they read current state and contribute updates. No direct agent-to-agent communication. Flexible but requires careful state management."
      },
      {
        type: "subheading",
        content: "6. Market-Based Coordination"
      },
      {
        type: "paragraph",
        content: "Agents bid on tasks based on their capabilities and current load. A coordinator assigns work to optimal bidders. Self-balancing under varying workloads."
      },
      {
        type: "paragraph",
        content: "In a hierarchical delegation setup, you define a manager agent (like a 'Research Director') with coordination tools, then create specialist agents with their own focused toolsets — a Market Analyst with financial data access, a Competitor Researcher with web scraping capabilities, and a Technical Analyst with code repository access. The manager delegates tasks, reviews outputs, and synthesizes the final result."
      },
      {
        type: "callout",
        variant: "tip",
        content: "Start with sequential pipelines for production systems. Add parallelism only where tasks are truly independent. Hierarchical patterns work best when you have clear specialist roles."
      },
      {
        type: "heading",
        content: "Protocol Standardization: MCP and A2A"
      },
      {
        type: "paragraph",
        content: "The agentic ecosystem matured rapidly in 2025-2026 as two critical protocols emerged: Anthropic's Model Context Protocol (MCP) for tool integration, and Google's Agent-to-Agent (A2A) protocol for inter-agent communication."
      },
      {
        type: "subheading",
        content: "Model Context Protocol (MCP)"
      },
      {
        type: "paragraph",
        content: "MCP standardizes how AI models connect to external tools and data sources. Think of it as 'USB-C for AI' — a universal interface that lets any MCP-compatible model use any MCP-compatible tool."
      },
      {
        type: "list",
        items: [
          "Open standard with implementations for major languages",
          "Tool discovery: agents can query available capabilities",
          "Secure authentication and permission scoping",
          "Adopted by Anthropic, OpenAI, Google, and major IDE vendors",
          "Production deployments at Block, Apollo, Replit, and hundreds of enterprises"
        ]
      },
      {
        type: "subheading",
        content: "Agent-to-Agent Protocol (A2A)"
      },
      {
        type: "paragraph",
        content: "A2A enables agents from different vendors to communicate and collaborate. An Anthropic Claude agent can delegate tasks to a Google Gemini agent, receive results, and integrate them seamlessly."
      },
      {
        type: "list",
        items: [
          "Vendor-agnostic agent communication",
          "Capability negotiation between agents",
          "Structured task delegation and result formatting",
          "Trust and authentication across organizational boundaries",
          "Critical for enterprise deployments with heterogeneous AI infrastructure"
        ]
      },
      {
        type: "callout",
        variant: "info",
        content: "The combination of MCP and A2A creates a composable agent ecosystem. Build specialized agents with focused capabilities, then orchestrate them into powerful workflows using standardized protocols."
      },
      {
        type: "heading",
        content: "Real-World Applications"
      },
      {
        type: "paragraph",
        content: "Agentic AI has moved far beyond chatbots. Here's where we're seeing the most impactful deployments:"
      },
      {
        type: "subheading",
        content: "Software Development"
      },
      {
        type: "paragraph",
        content: "Development agents don't just suggest code — they implement features end-to-end. Claude Code's agent teams can tackle complex refactoring across hundreds of files, run tests, fix failures, and submit pull requests. At M.D.N Tech, we use agentic workflows for:"
      },
      {
        type: "list",
        items: [
          "Automated code review with security analysis",
          "Test generation and maintenance",
          "Documentation sync as code changes",
          "Dependency updates with compatibility verification",
          "Legacy system modernization"
        ]
      },
      {
        type: "subheading",
        content: "Customer Operations"
      },
      {
        type: "paragraph",
        content: "Support agents now handle complex multi-step resolutions autonomously — checking order status, initiating refunds, scheduling callbacks, and escalating appropriately. The best implementations maintain context across channels and handoffs."
      },
      {
        type: "subheading",
        content: "Research and Analysis"
      },
      {
        type: "paragraph",
        content: "Research agents combine web search, document analysis, and synthesis to produce comprehensive reports. Investment firms use multi-agent systems for competitive intelligence. Legal teams deploy agents for contract analysis and due diligence."
      },
      {
        type: "subheading",
        content: "Business Process Automation"
      },
      {
        type: "paragraph",
        content: "Agentic RPA goes beyond traditional automation scripts. Agents understand intent, handle exceptions, and adapt to changing interfaces. They're replacing brittle rule-based systems with intelligent workflows that improve over time."
      },
      {
        type: "heading",
        content: "Architecture Deep Dive: Building Production Agents"
      },
      {
        type: "paragraph",
        content: "Production agentic systems require careful architectural decisions. Here's the reference architecture we use at M.D.N Tech:"
      },
      {
        type: "subheading",
        content: "Core Components"
      },
      {
        type: "list",
        items: [
          "Orchestrator: Manages agent lifecycle, task routing, and error handling",
          "Agent Registry: Tracks available agents, their capabilities, and current status",
          "Tool Server: MCP-compatible server exposing tools to agents",
          "Memory Layer: Short-term (conversation), long-term (knowledge base), and episodic (task history)",
          "Observation Pipeline: Logging, monitoring, and analytics for agent behavior",
          "Safety Layer: Input/output filtering, action approval, and rollback capabilities"
        ]
      },
      {
        type: "paragraph",
        content: "Each agent configuration includes: an identifier and role definition, the model powering it (Claude Opus, Sonnet, or alternatives), available tools, memory settings (short-term with TTL, long-term vector storage, episodic for task history), and safety controls (input/output filters, action approval mode, maximum actions per task, and rollback capabilities)."
      },
      {
        type: "subheading",
        content: "Memory Architecture"
      },
      {
        type: "paragraph",
        content: "Memory is the most underestimated component of agentic systems. Without proper memory architecture, agents repeat mistakes, lose context, and fail to learn from experience."
      },
      {
        type: "list",
        items: [
          "Working Memory: Current task context, recent conversation, active tool states",
          "Semantic Memory: Vector-indexed knowledge base for retrieval-augmented generation",
          "Episodic Memory: Historical task executions, outcomes, and learned corrections",
          "Procedural Memory: Successful patterns and workflows extracted from past performance"
        ]
      },
      {
        type: "callout",
        variant: "tip",
        content: "Episodic memory is the secret to agents that improve over time. Log full task trajectories including failures. Use them to fine-tune and to provide few-shot examples for similar future tasks."
      },
      {
        type: "heading",
        content: "Failure Modes and Mitigation"
      },
      {
        type: "paragraph",
        content: "Understanding why agents fail is as important as understanding how they work. The 90% failure rate for legacy agents stems from predictable anti-patterns:"
      },
      {
        type: "subheading",
        content: "1. Infinite Loops"
      },
      {
        type: "paragraph",
        content: "Agents get stuck repeating the same failed action. Mitigation: Implement loop detection, action budgets, and exponential backoff. After N failures of the same type, escalate or abort."
      },
      {
        type: "subheading",
        content: "2. Goal Drift"
      },
      {
        type: "paragraph",
        content: "Agents pursue emergent objectives that diverge from intended goals. Mitigation: Regular goal alignment checks, constrained action spaces, and human approval for high-impact decisions."
      },
      {
        type: "subheading",
        content: "3. Hallucinated Tools"
      },
      {
        type: "paragraph",
        content: "Agents attempt to use tools that don't exist or use real tools incorrectly. Mitigation: Strict tool schemas, validation on all tool calls, graceful error handling with retry logic."
      },
      {
        type: "subheading",
        content: "4. Context Overflow"
      },
      {
        type: "paragraph",
        content: "Long-running tasks exceed context windows, causing agents to 'forget' critical information. Mitigation: Summarization strategies, hierarchical memory, and task checkpointing."
      },
      {
        type: "subheading",
        content: "5. Cascading Failures"
      },
      {
        type: "paragraph",
        content: "One agent failure propagates through a multi-agent system. Mitigation: Circuit breakers, isolated failure domains, and fallback agents."
      },
      {
        type: "paragraph",
        content: "A robust execution flow includes several safeguards: loop detection (comparing current action against history), action budget enforcement (limiting total actions per task), timeout handling for each action, and exponential backoff on retries. When the budget is exceeded or max retries are reached, the system returns partial results with a summary of what was accomplished before the failure."
      },
      {
        type: "heading",
        content: "Enterprise Deployment Considerations"
      },
      {
        type: "paragraph",
        content: "Deploying agentic systems in enterprise environments requires addressing concerns that don't exist for simple API integrations:"
      },
      {
        type: "subheading",
        content: "Governance and Compliance"
      },
      {
        type: "list",
        items: [
          "Audit trails: Log all agent decisions, tool calls, and outcomes",
          "Explainability: Provide reasoning traces for agent actions",
          "Access control: Scope agent permissions to minimum necessary",
          "Data residency: Ensure agent processing respects geographic constraints",
          "Model governance: Track which models power which agents, manage updates"
        ]
      },
      {
        type: "subheading",
        content: "Security"
      },
      {
        type: "list",
        items: [
          "Prompt injection defense: Validate all inputs, especially from external sources",
          "Tool permission scoping: Agents should have least-privilege access",
          "Secrets management: Never expose credentials in agent context",
          "Network isolation: Restrict agent network access to required endpoints",
          "Output filtering: Prevent data exfiltration through agent responses"
        ]
      },
      {
        type: "callout",
        variant: "warning",
        content: "Agentic systems with broad tool access are high-value targets. Treat them like you would any privileged automated system — with defense in depth, monitoring, and incident response plans."
      },
      {
        type: "heading",
        content: "The Road Ahead"
      },
      {
        type: "paragraph",
        content: "Agentic AI is evolving rapidly. Here's what we're watching for the next 12-24 months:"
      },
      {
        type: "list",
        items: [
          "Reasoning improvements: Models with better planning and self-correction will reduce failure rates dramatically",
          "Specialized agents: Purpose-built agents for specific domains (legal, medical, financial) with domain-specific training",
          "Agent marketplaces: Ecosystems where pre-built agents can be composed into workflows",
          "Hardware acceleration: Dedicated inference infrastructure optimized for agentic workloads",
          "Regulatory frameworks: Compliance requirements for autonomous AI systems in regulated industries",
          "Human-agent collaboration: Better interfaces for humans to supervise, guide, and collaborate with agent teams"
        ]
      },
      {
        type: "callout",
        variant: "stat",
        content: "Gartner predicts 33% of enterprise software applications will include agentic AI by 2028, up from less than 1% in 2024. The transformation is happening now."
      },
      {
        type: "heading",
        content: "Getting Started"
      },
      {
        type: "paragraph",
        content: "Ready to build agentic systems? Here's our recommended progression:"
      },
      {
        type: "list",
        items: [
          "Start with single agents: Build one agent with clear tools and objectives. Master reliability before adding complexity",
          "Implement proper observability: Logging, tracing, and monitoring from day one. You can't improve what you can't see",
          "Add memory incrementally: Start with conversation memory, add semantic search, then episodic learning",
          "Design for failure: Assume agents will fail. Build graceful degradation and recovery into your architecture",
          "Scale to multi-agent gradually: Only add agents when you have clear specialization boundaries",
          "Establish governance early: Audit trails and access controls are easier to add before production scale"
        ]
      },
      {
        type: "paragraph",
        content: "The teams that master agentic AI now will have compounding advantages as the technology matures. The patterns are emerging, the protocols are standardizing, and the infrastructure is ready. The question is whether you'll be building with agents or competing against those who are."
      },
      {
        type: "heading",
        content: "Conclusion"
      },
      {
        type: "paragraph",
        content: "Agentic AI represents the most significant shift in enterprise software since cloud computing. We're moving from systems that require human orchestration to systems that orchestrate themselves — planning, executing, learning, and adapting autonomously."
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, we've seen firsthand how agentic systems transform what's possible. Tasks that required teams of engineers now complete autonomously. Workflows that took weeks execute in hours. And the pace of improvement is accelerating."
      },
      {
        type: "paragraph",
        content: "The organizations that thrive will be those that learn to architect, deploy, and govern agentic systems effectively. The technology is ready. The question is whether your team is ready to build with it."
      },
      {
        type: "callout",
        variant: "info",
        content: "Building agentic AI systems? Our team has deployed production agents across industries. Contact us to discuss your use case and architecture."
      }
    ]
  },
  {
    id: "smart-contracts-complete-guide",
    title: "Smart Contract Development: ERC Standards, Security, and Chainlink VRF",
    excerpt: "Master EVM smart contract development with this comprehensive guide covering ERC-20, ERC-721, ERC-1155 standards, security best practices, and Chainlink VRF for provably fair randomness.",
    metaDescription: "Complete guide to EVM smart contract development. Learn ERC-20, ERC-721, ERC-1155 standards, security best practices, Chainlink VRF integration, and lessons from 50+ deployments.",
    image: "/blog/smart-contracts-guide.jpg",
    category: "Blockchain & Web3",
    date: "March 1, 2026",
    readTime: "18 min read",
    author: "M.D.N Tech Team",
    authorRole: "Web3 Development Experts",
    tags: ["Smart Contracts", "Solidity", "ERC-721", "ERC-1155", "Chainlink VRF", "Web3 Security"],
    content: [
      {
        type: "paragraph",
        content: "Smart contracts are the backbone of decentralized applications, DeFi protocols, and NFT ecosystems. At M.D.N Tech, we've deployed over 50 production smart contracts across multiple chains — from token launches and NFT collections to complex DeFi mechanisms and on-chain lotteries. This guide distills everything we've learned about building secure, gas-efficient, and production-ready smart contracts."
      },
      {
        type: "callout",
        variant: "stat",
        content: "Chainlink secures over $100 billion in Total Value Secured (TVS) and has enabled $27+ trillion in transaction value across 60+ blockchains."
      },
      {
        type: "paragraph",
        content: "Whether you're building your first ERC-20 token or implementing Chainlink VRF for provably fair NFT minting, this guide covers the standards, security practices, and real-world patterns that separate amateur contracts from production-grade infrastructure."
      },
      {
        type: "heading",
        content: "The State of Smart Contract Security in 2026"
      },
      {
        type: "paragraph",
        content: "Before diving into development, let's look at the current landscape. The numbers are sobering — and instructive."
      },
      {
        type: "callout",
        variant: "warning",
        content: "$3.1 billion was lost across Web3 in the first half of 2025 alone — already surpassing all of 2024. 9 out of 10 hacked protocols had passed security audits."
      },
      {
        type: "paragraph",
        content: "The key insight? Audits are necessary but not sufficient. The median time between a protocol passing an audit and getting exploited is just 47 days. The teams that survive build multiple defense layers: development-time analysis, pre-launch audits, live bug bounties, on-chain monitoring, and financial backstops."
      },
      {
        type: "list",
        items: [
          "Access control exploits caused $1.83 billion in losses (mostly Q1 2025)",
          "Reentrancy and logic bugs led to $325 million in stolen assets",
          "Phishing and social engineering spiked to $600 million",
          "Smart contract bugs caused approximately $263 million in damages",
          "About 70% of smart contracts on Ethereum are inactive or vulnerable"
        ]
      },
      {
        type: "paragraph",
        content: "With this context, let's explore how to build contracts that don't become statistics."
      },
      {
        type: "heading",
        content: "ERC-20: Token Contracts Done Right"
      },
      {
        type: "paragraph",
        content: "ERC-20 remains the foundation of fungible tokens on Ethereum and EVM-compatible chains. Despite being well-established, ERC-20 implementations still account for significant vulnerabilities."
      },
      {
        type: "subheading",
        content: "Common ERC-20 Vulnerabilities"
      },
      {
        type: "list",
        items: [
          "Integer Overflow/Underflow: The BeautyChain (BEC) hack exploited batch overflow to mint astronomical token amounts. Always use SafeMath or Solidity 0.8+ built-in checks",
          "Approval Frontrunning: The approve() function directly sets allowance, enabling frontrunning attacks. Use safeIncreaseAllowance and safeDecreaseAllowance instead",
          "Lost Token Problem: Users sending tokens to contracts without extraction functions have caused $27+ million in permanent losses",
          "Reentrancy via Hooks: ERC-777's receive hooks, while useful, enable both reentrancy and DoS attacks"
        ]
      },
      {
        type: "paragraph",
        content: "A secure ERC-20 implementation extends OpenZeppelin's ERC20, ERC20Burnable, and Ownable contracts. Key features include: a maximum supply constant, constructor that mints the full supply to the deployer, and a rescue function that allows the owner to recover accidentally sent tokens (with a safeguard preventing rescue of the contract's own tokens)."
      },
      {
        type: "callout",
        variant: "tip",
        content: "Always use OpenZeppelin's battle-tested implementations as your foundation. Their contracts are audited, widely used, and continuously maintained."
      },
      {
        type: "subheading",
        content: "ERC-20 Security Best Practices"
      },
      {
        type: "list",
        items: [
          "Use Solidity 0.8+ for built-in overflow protection",
          "Implement rescue functions for accidentally sent tokens",
          "Use pull over push patterns for distributions (airdrops, bonuses)",
          "Limit approval amounts — avoid unlimited approvals",
          "Include pause functionality for emergency situations",
          "Test on testnets with realistic scenarios before mainnet"
        ]
      },
      {
        type: "heading",
        content: "ERC-721 vs ERC-1155: Choosing the Right NFT Standard"
      },
      {
        type: "paragraph",
        content: "Both standards serve NFT use cases, but they're designed for different scenarios. Understanding when to use each is crucial for gas efficiency and user experience."
      },
      {
        type: "subheading",
        content: "ERC-721: The Original NFT Standard"
      },
      {
        type: "paragraph",
        content: "ERC-721, introduced in 2017, established the foundation for NFTs. Each token is unique and requires individual tracking. This makes it ideal for truly unique assets like digital art, domain names, or real estate tokens."
      },
      {
        type: "list",
        items: [
          "One contract per collection",
          "Each token has unique metadata",
          "Higher gas costs for batch operations",
          "Universal wallet and marketplace support",
          "Best for: 1/1 art, PFP collections, unique collectibles"
        ]
      },
      {
        type: "subheading",
        content: "ERC-1155: The Multi-Token Standard"
      },
      {
        type: "paragraph",
        content: "ERC-1155 allows a single contract to manage multiple token types — both fungible and non-fungible. It supports batch transfers, reducing gas costs by up to 90% for multi-item operations."
      },
      {
        type: "list",
        items: [
          "Multiple token types in one contract",
          "Batch transfers in single transaction (up to 150-200 tokens)",
          "Built-in safe transfer verification",
          "Semi-fungible token support (editions)",
          "Best for: Gaming items, trading cards, multi-edition collectibles"
        ]
      },
      {
        type: "paragraph",
        content: "For gaming items with random attributes, the implementation extends ERC-1155 and integrates Chainlink VRF. Token IDs represent different rarity tiers (common, rare, legendary). When a user mints, the contract requests randomness from Chainlink. Once fulfilled, the random number determines rarity — typically 5% legendary, 15% rare, 80% common. The token is then minted to the user's address with the determined rarity."
      },
      {
        type: "callout",
        variant: "info",
        content: "Real-world example: Axie Infinity used Chainlink VRF to give each of 4,088 Origin Axies truly random characteristics across six body parts, ensuring provably fair distribution."
      },
      {
        type: "heading",
        content: "Chainlink VRF: Provably Fair Randomness"
      },
      {
        type: "paragraph",
        content: "Blockchain networks are deterministic by design — every node executes the same transactions and reaches identical results. This creates a fundamental challenge: how do you generate truly random numbers on a predictable system?"
      },
      {
        type: "paragraph",
        content: "Chainlink VRF (Verifiable Random Function) solves this by generating random values off-chain with cryptographic proof that the results weren't tampered with. The proof is verified on-chain before any consuming application can use it."
      },
      {
        type: "callout",
        variant: "stat",
        content: "Chainlink VRF has fulfilled 20+ million request transactions for thousands of smart contracts across multiple blockchains, making it the most widely adopted RNG in Web3."
      },
      {
        type: "subheading",
        content: "VRF Use Cases We've Implemented"
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, we've used Chainlink VRF extensively. Here are the primary patterns:"
      },
      {
        type: "list",
        items: [
          "On-chain Lotteries: Fair winner selection for raffles and prize pools. PancakeSwap's Lottery V2 uses VRF for publicly auditable drawings",
          "Random NFT Attributes: Generating rarity traits during minting. Bored Ape Yacht Club used VRF to distribute Mutant Serum NFTs fairly",
          "Loot Box Mechanics: Provably fair item drops for gaming. CryptoBlades uses VRF for unpredictable battle pairings",
          "Random Matchmaking: Fair player pairing in competitive games without manipulation",
          "Dynamic NFTs: NFTs that 'evolve' with random characteristics over time"
        ]
      },
      {
        type: "subheading",
        content: "Implementing VRF v2.5"
      },
      {
        type: "paragraph",
        content: "Chainlink VRF v2.5 offers two payment models: subscription-based (best for frequent requests) and direct funding (best for one-off requests like NFT distributions)."
      },
      {
        type: "paragraph",
        content: "A VRF-powered lottery contract manages player entries, prize pool accumulation, and provably fair winner selection. Players enter by sending ETH above the minimum threshold. When the owner triggers winner selection, the contract enters a 'calculating' state and requests randomness from Chainlink VRF. Once the random number arrives, it's used to select a winner index from the player array. The prize pool is transferred to the winner, and the lottery resets for the next round."
      },
      {
        type: "callout",
        variant: "tip",
        content: "For gaming platforms with frequent randomness needs, use the subscription model. For NFT mints and one-time contests, direct funding keeps things simple."
      },
      {
        type: "heading",
        content: "Smart Contract Security Best Practices"
      },
      {
        type: "paragraph",
        content: "Based on our 50+ deployments and analysis of major exploits, here are the security practices that actually prevent hacks:"
      },
      {
        type: "subheading",
        content: "1. Follow the Checks-Effects-Interactions Pattern"
      },
      {
        type: "paragraph",
        content: "The most important defense against reentrancy attacks. Always: check conditions, update state, then interact with external contracts."
      },
      {
        type: "paragraph",
        content: "The vulnerable pattern makes an external call before updating state — allowing attackers to re-enter the function before the balance is zeroed. The correct pattern follows three steps: Check (verify balance exists), Effect (set balance to zero), Interaction (transfer funds). By updating state before the external call, even if the recipient tries to re-enter, they'll find their balance already zeroed."
      },
      {
        type: "subheading",
        content: "2. Implement Proper Access Control"
      },
      {
        type: "paragraph",
        content: "Access control failures caused $1.83 billion in losses in early 2025. Use OpenZeppelin's AccessControl or Ownable2Step for safe ownership transfers."
      },
      {
        type: "list",
        items: [
          "Use multi-sig wallets for admin functions",
          "Implement timelocks for critical operations",
          "Separate roles: admin, pauser, minter, upgrader",
          "Never use tx.origin for authentication",
          "Consider social recovery mechanisms"
        ]
      },
      {
        type: "subheading",
        content: "3. Validate All Inputs"
      },
      {
        type: "paragraph",
        content: "Lack of input validation accounts for 34.6% of direct contract exploits. Validate every external input, especially:"
      },
      {
        type: "list",
        items: [
          "Array lengths (prevent gas griefing)",
          "Address parameters (check for zero address)",
          "Numeric bounds (amounts, percentages, timestamps)",
          "String/bytes length limits",
          "Token decimals assumptions"
        ]
      },
      {
        type: "subheading",
        content: "4. Use Upgradeable Patterns Carefully"
      },
      {
        type: "paragraph",
        content: "Upgradeability is now critical infrastructure — and one of the most severe attack vectors. UUPS has won the efficiency battle but requires rigorous deployment discipline."
      },
      {
        type: "callout",
        variant: "warning",
        content: "By 2026, AI-driven audit processes compare bytecode between versions to detect storage slot shifts and invariant violations before upgrade transactions are signed. Consider integrating these tools."
      },
      {
        type: "heading",
        content: "Development Tools: Foundry vs Hardhat"
      },
      {
        type: "paragraph",
        content: "The tooling ecosystem has consolidated around two frameworks: Hardhat (60% market share) and Foundry (30% and growing). Many teams use both."
      },
      {
        type: "subheading",
        content: "Hardhat"
      },
      {
        type: "list",
        items: [
          "JavaScript-first approach with rich plugin ecosystem",
          "console.log() debugging inside Solidity",
          "Detailed stack traces and error messages",
          "Mainnet forking for local testing",
          "Hardhat 3 now supports both Solidity and TypeScript tests natively"
        ]
      },
      {
        type: "subheading",
        content: "Foundry"
      },
      {
        type: "list",
        items: [
          "Solidity-native testing (write tests in Solidity)",
          "2-5x faster compilation, up to 100x faster tests",
          "Powerful cheatcodes for EVM state manipulation",
          "Built-in fuzz testing for edge case discovery",
          "CLI tools: forge (build/test), cast (EVM CLI), anvil (local node)"
        ]
      },
      {
        type: "paragraph",
        content: "Foundry's fuzz testing automatically generates hundreds of random inputs to test edge cases. A fuzz test for token transfers might verify that for any transfer amount (bounded to available balance), the sender's balance decreases by exactly that amount while the receiver's increases by exactly that amount. This catches edge cases like boundary conditions and overflow scenarios that manual tests often miss."
      },
      {
        type: "callout",
        variant: "tip",
        content: "Start with Hardhat if you're comfortable with JavaScript. Move to Foundry for faster iteration and Solidity-native testing. Many production teams use both."
      },
      {
        type: "heading",
        content: "Chainlink Ecosystem: Beyond VRF"
      },
      {
        type: "paragraph",
        content: "Chainlink dominates the oracle market with 67% market share. On Ethereum, it secures over 83% of Total Value Secured; on Base, nearly 100%. Here's what else the ecosystem offers:"
      },
      {
        type: "list",
        items: [
          "Price Feeds: Real-time asset prices for DeFi protocols (Aave alone secures $70+ billion using Chainlink)",
          "Automation (Keepers): Decentralized contract automation for periodic tasks",
          "CCIP: Cross-chain interoperability across 60+ blockchains",
          "Functions: Run custom computations off-chain with on-chain verification",
          "Data Streams: High-frequency data with 777% throughput increase in Q1 2025",
          "Proof of Reserve: Verify off-chain collateral for wrapped assets"
        ]
      },
      {
        type: "heading",
        content: "Real-World Architecture: NFT Collection with Random Traits"
      },
      {
        type: "paragraph",
        content: "Here's a production architecture we've used for NFT collections requiring provably fair attribute generation:"
      },
      {
        type: "paragraph",
        content: "A production NFT collection with random traits combines ERC-721 Enumerable, Ownable, ReentrancyGuard, and Chainlink VRF. Each trait category (background, body, accessory, head, eyes) has its own range of possible values. When minting, the contract first mints the NFT, then requests randomness. Once Chainlink fulfills the request, the single random number is bit-shifted to derive independent random values for each trait category, plus an overall rarity score. The traits are stored on-chain and an event is emitted for indexers."
      },
      {
        type: "heading",
        content: "Audit Checklist: Before You Deploy"
      },
      {
        type: "paragraph",
        content: "Comprehensive audits cost $25,000-$150,000 depending on complexity. Simple ERC-20 audits run $8,000-$20,000, while complex DeFi protocols can exceed $150,000. Here's what to verify before seeking an audit:"
      },
      {
        type: "list",
        items: [
          "All external calls follow checks-effects-interactions",
          "Access control covers all admin functions",
          "Input validation on all public/external functions",
          "No hardcoded addresses that should be configurable",
          "Events emitted for all state changes",
          "Reentrancy guards on functions with external calls",
          "Proper handling of ETH transfers (check return values)",
          "Gas optimization reviewed (loops, storage, calldata vs memory)",
          "Emergency pause functionality implemented",
          "Upgrade mechanisms tested thoroughly",
          "100% test coverage with edge cases",
          "Fuzz testing for mathematical operations"
        ]
      },
      {
        type: "heading",
        content: "Conclusion"
      },
      {
        type: "paragraph",
        content: "Smart contract development has matured significantly, but the stakes have never been higher. With billions at risk and increasingly sophisticated attackers, building secure contracts requires deep understanding of standards, security patterns, and battle-tested tooling."
      },
      {
        type: "paragraph",
        content: "At M.D.N Tech, we've learned that success comes from combining proven patterns (OpenZeppelin, Chainlink), rigorous testing (Foundry fuzz testing), and multiple security layers. The contracts that survive are the ones built with security as a first principle, not an afterthought."
      },
      {
        type: "paragraph",
        content: "Whether you're building a simple token, a complex NFT collection with random traits, or a full DeFi protocol, the fundamentals remain the same: use established standards, verify everything, and never underestimate the creativity of attackers."
      },
      {
        type: "callout",
        variant: "info",
        content: "Ready to build secure smart contracts? Our Web3 team has deployed 50+ production contracts across multiple chains. Contact us to discuss your project."
      }
    ]
  },
];

// Helper function to get post by ID
export function getPostById(id: string): BlogPost | undefined {
  return BLOG_POSTS.find(post => post.id === id);
}

// Helper function to get all posts
export function getAllPosts(): BlogPost[] {
  return BLOG_POSTS;
}

// Helper function to get posts by category
export function getPostsByCategory(category: string): BlogPost[] {
  return BLOG_POSTS.filter(post => post.category === category);
}

// Helper function to get related posts (same category, excluding current)
export function getRelatedPosts(currentId: string, limit: number = 3): BlogPost[] {
  const currentPost = getPostById(currentId);
  if (!currentPost) return [];

  return BLOG_POSTS
    .filter(post => post.id !== currentId && post.category === currentPost.category)
    .slice(0, limit);
}
