'use client'

import { Download } from 'lucide-react'

type Entry = { title: string; category: string; content: string }

export function KBExportButton({ chatbotName, entries }: { chatbotName: string; entries: Entry[] }) {
  function handleExport() {
    const categoryOrder = ['about', 'tone', 'products', 'pricing', 'faq', 'policies', 'support', 'general', 'other']
    const grouped = entries.reduce((acc: Record<string, Entry[]>, e) => {
      acc[e.category] = [...(acc[e.category] ?? []), e]
      return acc
    }, {})

    const sorted = [
      ...categoryOrder.filter(c => grouped[c]),
      ...Object.keys(grouped).filter(c => !categoryOrder.includes(c)),
    ]

    const lines: string[] = [
      `# ${chatbotName} -- Knowledge Base`,
      ``,
      `> Generated by M.D.N Tech Command Center`,
      `> Exported: ${new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' })}`,
      ``,
      `---`,
      ``,
    ]

    for (const cat of sorted) {
      lines.push(`## ${cat.charAt(0).toUpperCase() + cat.slice(1)}`)
      lines.push(``)
      for (const entry of grouped[cat]) {
        lines.push(`### ${entry.title}`)
        lines.push(``)
        lines.push(entry.content.trim())
        lines.push(``)
        lines.push(`---`)
        lines.push(``)
      }
    }

    const blob = new Blob([lines.join('\n')], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${chatbotName.toLowerCase().replace(/\s+/g, '-')}-knowledge-base.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <button
      onClick={handleExport}
      disabled={entries.length === 0}
      title="Export full knowledge base as .md"
      className="flex items-center gap-1.5 px-3 py-1.5 text-xs text-gray-400 border border-white/10 hover:border-white/20 hover:text-white rounded-lg transition-colors disabled:opacity-40 disabled:cursor-not-allowed"
    >
      <Download className="w-3.5 h-3.5" />
      Export .md
    </button>
  )
}
